apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fmjqb0wow-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fmjqb0wow-java-quarkus-gitops